[CmdletBinding()]
param()

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

function Assert-Condition {
    param(
        [Parameter(Mandatory)]
        [bool]$Condition,

        [Parameter(Mandatory)]
        [string]$Message
    )

    if (-not $Condition) {
        throw $Message
    }
}

$synchronizer = Join-Path $PSScriptRoot 'sync_input.ps1'
$temporaryRoot = Join-Path (
    [IO.Path]::GetTempPath()
) ('na2-input-profile-test-{0}' -f [guid]::NewGuid().ToString('N'))

New-Item -ItemType Directory -Path $temporaryRoot | Out-Null
try {
    $basePath = Join-Path $temporaryRoot 'Base.ini'
    $outputPath = Join-Path $temporaryRoot 'Base_NA2.ini'
    $linkedOutputPath = Join-Path $temporaryRoot 'PCSX2_Base_NA2.ini'
    $baseText = @'
[Pad1]
Type = DualShock2

Triangle = SDL-0/FaceNorth
Circle = SDL-0/FaceEast
Cross = SDL-0/FaceSouth
Square = SDL-0/FaceWest

Triangle = Keyboard/I
Circle = Keyboard/L
Cross = Keyboard/K
Square = Keyboard/J

[Pad2]
Triangle = untouched
'@ -replace "`r`n", "`n"
    [IO.File]::WriteAllBytes(
        $basePath,
        [Text.Encoding]::Latin1.GetBytes($baseText)
    )
    [IO.File]::WriteAllText($outputPath, "stale`r`n")
    New-Item `
        -ItemType HardLink `
        -Path $linkedOutputPath `
        -Target $outputPath |
        Out-Null

    $first = & $synchronizer `
        -BasePath $basePath `
        -OutputPath $outputPath `
        -PassThru
    Assert-Condition $first.Changed 'The stale generated profile was not updated.'

    $expectedText = (
        $baseText.
            Replace('Triangle = SDL-0/FaceNorth', 'Triangle = SDL-0/FaceEast').
            Replace('Circle = SDL-0/FaceEast', 'Circle = SDL-0/FaceSouth').
            Replace('Cross = SDL-0/FaceSouth', 'Cross = SDL-0/FaceNorth')
    )
    $actualBytes = [IO.File]::ReadAllBytes($outputPath)
    $expectedBytes = [Text.Encoding]::Latin1.GetBytes($expectedText)
    Assert-Condition `
        ([Convert]::ToHexString($actualBytes) -ceq
            [Convert]::ToHexString($expectedBytes)) `
        'Generated bytes differ outside the configured Pad1 bindings.'
    Assert-Condition `
        ([Convert]::ToHexString([IO.File]::ReadAllBytes($linkedOutputPath)) -ceq
            [Convert]::ToHexString($expectedBytes)) `
        'Updating the generated profile broke its existing hardlink.'

    $firstWriteTime = (Get-Item -LiteralPath $outputPath).LastWriteTimeUtc
    Start-Sleep -Milliseconds 50
    $second = & $synchronizer `
        -BasePath $basePath `
        -OutputPath $outputPath `
        -PassThru
    Assert-Condition (-not $second.Changed) 'The second run was not idempotent.'
    Assert-Condition `
        ((Get-Item -LiteralPath $outputPath).LastWriteTimeUtc -eq $firstWriteTime) `
        'The second run rewrote an already-current generated profile.'

    Write-Host 'Input-profile synchronization tests passed.'
}
finally {
    Remove-Item -LiteralPath $temporaryRoot -Recurse -Force -ErrorAction SilentlyContinue
}
